apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: heimdall-injector
rules:
- apiGroups: ["", "apps"]
  resources: ["configmaps", "deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]